name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master # Zure adar nagusia 'main' bada, aldatu 'main'-era

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Proiektuak behar duen Node.js bertsioa

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
        env:
    NODE_OPTIONS: "--openssl-legacy-provider"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Eraikitako fitxategiak dauden karpeta
